"""empty message

Revision ID: cd2a76016e88
Revises: b935cf54e49c
Create Date: 2016-03-20 21:50:24.495034

"""

# revision identifiers, used by Alembic.
revision = 'cd2a76016e88'
down_revision = 'b935cf54e49c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shippingadd', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shippingadd')
    ### end Alembic commands ###
